{
 "title": "ControlD",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Activity Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Devices",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"deviceId\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Action Trigger Filters Native :: Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"actionTriggerFull\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Action Trigger",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"actionTrigger\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Action Trigger :: Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"actionTriggerDevice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Action Trigger Value",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"actionTriggerValue\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Action Trigger Value :: Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"actionTriggerValueDevice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Action Spoof Target",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"actionSpoofTarget\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Action Spoof Target :: Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"actionSpoofTargetDevice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"protocol\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Protocol :: Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"protocolDevice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"rrType\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Type :: Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"rrTypeDevice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source IP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"sourceIp\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source IP :: Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"sourceIpDevice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source Geo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"sourceGeoip\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source Geo :: Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"sourceGeoipDevice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source ISP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"sourceIsp\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source ISP :: Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"sourceIspDevice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Question Domain :: First",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"questionDomainFirst\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Question Domain :: Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "topk(5, ctrld_devices_activity_log{activity=\"questionDomainSecond\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Answer Country",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"answersCountry\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Answer ISP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "topk(5, ctrld_devices_activity_log{activity=\"answersIsp\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Statistics [week]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"all-by-verdict-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Blocked By Filter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 101 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"blocked-by-filter-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Triggered By Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 101 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"service-triggered-by-service-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Redirected By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"redirected-by-domain-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Redirected By Location",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"redirected-by-location-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bypassed By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"bypassed-by-domain-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Blocked By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 119 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"blocked-by-domain-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Statistics [month]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"all-by-verdict-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Blocked By Filter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 129 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"blocked-by-filter-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Triggered By Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 129 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"service-triggered-by-service-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Redirected By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"redirected-by-domain-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Redirected By Location",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 138 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"redirected-by-location-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bypassed By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"bypassed-by-domain-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Blocked By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 147 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"blocked-by-domain-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 } },
  {
   "title": "Inner Stat",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 157 },
   "targets": [
    { "expr": "ctrld_counters", "legendFormat": "{{type}}" },
    { "expr": "ctrld_locations", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ctrld_version", "legendFormat": "version" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ctrld_latency", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Last Request",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "ctrld_devices_last_activity * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Changelog",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 166 },
   "targets": [
    { "expr": "ctrld_changelog", "legendFormat": "{{text}}" }
   ]
  }
 ]
}