{
 "title": "Prometheus",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Processes Start",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "process_start_time_seconds * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Samples Scrape Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(scrape_series_added[60m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_http_requests_total[60m])",
     "legendFormat": "{{code}} | {{handler}}"
    }
   ]
  },
  {
   "title": "Time Series Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_series_created_total[60m])",
     "legendFormat": "created"
    },
    {
     "expr": "increase(prometheus_tsdb_head_series_removed_total[60m])",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "count" }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "prometheus_tsdb_head_chunks", "legendFormat": "count" }
   ]
  },
  {
   "title": "Top Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(30, count by (__name__)({__name__=~\".+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (job)({__name__=~\".+\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}