{
 "title": "System",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(sys_uptime,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "_", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_uptime{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(sys_cpus{instance=\"$instance\"}[60s]) / 60",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sys_load{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "sys_mem{type=\"MemTotal\", instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "sys_mem{type=\"MemUsed\", instance=\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "sys_mem{type=\"SwapTotal\", instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "sys_mem{type=\"SwapUsed\", instance=\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "FS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "sys_fs{type=\"total\", instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "sys_fs{type=\"used\", instance=\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "IO Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "increase(sys_io{type=\"read\", instance=\"$instance\"}[60m])",
     "legendFormat": "{{name}}: {{type}}"
    },
    {
     "expr": "increase(sys_io{type=\"write\", instance=\"$instance\"}[60m])",
     "legendFormat": "{{name}}: {{type}}"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sys_mem{type=\"Apps\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"PageTables\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"SwapCached\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"Slab\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"Cached\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"Buffers\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"MemFree\", instance=\"$instance\"}",
     "legendFormat": "Unused"
    },
    {
     "expr": "sys_mem{type=\"SwapUsed\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"HardwareCorrupted\", instance=\"$instance\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network Traffic Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(sys_network{instance=\"$instance\"}[60m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Procs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sys_procs{name=\"count\", instance=\"$instance\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_procs{name=\"cpu\", instance=\"$instance\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_procs{name=\"mem\", instance=\"$instance\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Systemd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Unit States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sys_systemd{name=\"count\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sys_systemd{name=\"failed\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Apt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sys_apt{instance=\"$instance\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Installed Packages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sys_pkg{instance=\"$instance\"}",
     "legendFormat": "count"
    }
   ]
  },
  { "title": "Ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Open",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sys_ports{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "UFW Rules",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sys_ufw{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "F2B",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bans",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sys_f2b{name=\"totalBanned\", instance=\"$instance\"} > 0",
       "legendFormat": "{{type}} | {{name}}"
      },
      {
       "expr": "sys_f2b{name=\"currentlyBanned\", instance=\"$instance\"} > 0",
       "legendFormat": "{{type}} | {{name}}"
      }
     ]
    },
    {
     "title": "Fails",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sys_f2b{name=\"totalFailed\", instance=\"$instance\"} > 0",
       "legendFormat": "{{type}} | {{name}}"
      },
      {
       "expr": "sys_f2b{name=\"currentlyFailed\", instance=\"$instance\"} > 0",
       "legendFormat": "{{type}} | {{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Certs Valid Days",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sys_certbot{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sys_temp{instance=\"$instance\"}",
     "legendFormat": "{{type}}{{zone}}"
    }
   ]
  }
 ]
}