{
 "title": "VDSina",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    { "expr": "vdsina_balance", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "vdsina_bandwidth", "legendFormat": "{{server}} | {{type}}" }
   ]
  },
  { "title": "Average per hour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vdsina_stats{type=\"cpu\"}",
     "legendFormat": "{{server}} | {{type}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "vdsina_stats{type=\"disk_reads\"} / 3600",
     "legendFormat": "{{server}} | {{type}}"
    },
    {
     "expr": "vdsina_stats{type=\"disk_writes\"} / 3600",
     "legendFormat": "{{server}} | {{type}}"
    }
   ]
  },
  {
   "title": "Net",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vdsina_stats{type=\"vnet_rx\"}",
     "legendFormat": "{{server}} | {{type}}"
    },
    {
     "expr": "vdsina_stats{type=\"vnet_tx\"}",
     "legendFormat": "{{server}} | {{type}}"
    }
   ]
  }
 ]
}