{
 "title": "Mikrotik",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mik_system_resource{type=\"uptime\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Current Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mik_system_package_update{type=\"installed-version\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Latest Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mik_system_package_update{type=\"latest-version\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Channel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mik_system_package_update{type=\"channel\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mik_system_package_update{type=\"status\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mik_system_resource{type=\"cpu-load\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CPU Freq",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "mik_system_resource{type=\"cpu-frequency\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "mik_system_resource{type=\"used-memory\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "mik_system_resource{type=\"total-memory\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "HDD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "mik_system_resource{type=\"used-hdd-space\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "mik_system_resource{type=\"total-hdd-space\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "mik_ip_dns{type=\"cache-used\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Records",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_dns_cache{type=\"records\"}",
     "legendFormat": "{{record}}"
    }
   ]
  },
  {
   "title": "Redirect Src",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_log{type=\"redirect-dns-src\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Redirect Dest",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_log{type=\"redirect-dns-dest\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Redirect Proto",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_log{type=\"redirect-dns-proto\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Redirect Full",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_log{type=\"redirect-dns-full\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Bytes Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(mik_interface{type=\"bytes\"}[60m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bytes Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "mik_interface{type=\"bytes_per_sec\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_interface{type=\"errors\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Wireless", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_interface_wireless{type=\"registered-clients\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CCQ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mik_interface_wireless{type=\"overall-tx-ccq\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Noise Floor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "mik_interface_wireless{type=\"noise-floor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CCQ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mik_interface_wireless_registration_table{type=\"ccq\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bytes Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(mik_interface_wireless_registration_table{type=\"bytes\"}[60m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Signal To Noise",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "mik_interface_wireless_registration_table{type=\"signal-to-noise\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "mik_interface_wireless_registration_table{type=\"signal-strength\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Wireguard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Bytes Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(mik_interface_wireguard_peers{type=\"bytes\"}[60m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Firewall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Filter Bytes Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(mik_ip_firewall_filter{type=\"bytes\"}[60m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nat Bytes Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(mik_ip_firewall_nat{type=\"bytes\"}[60m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mangle Bytes Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(mik_ip_firewall_mangle{type=\"bytes\"}[60m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Raw Bytes Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "increase(mik_ip_firewall_raw{type=\"bytes\"}[60m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Address List Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_address_list{type=\"count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "To VPN Dynamic Domains",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_address_list{type=\"dynamic-to-vpn-domains-list\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Honeypot Country",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_address_list{type=\"geoip_country\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Honeypot ISP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_address_list{type=\"geoip_isp\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Bytes Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(mik_queue_tree{type=\"bytes\"}[60m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queued Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mik_queue_tree{type=\"queued-bytes\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "mik_queue_tree{type=\"rate\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_queue_tree{type=\"dropped\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "Source Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_connection{type=\"src-name-count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Destination Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_connection{type=\"dst-host-bytes\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_connection{type=\"protocol-count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FastTrack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_connection{type=\"fasttrack-count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Destination Country",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_connection{type=\"dst-country\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Destination ISP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_ip_firewall_connection{type=\"dst-isp\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Scripts & Schedule", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 191 } },
  {
   "title": "Scheduler Runs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_system_scheduler{type=\"run-count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Scripts Runs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_system_script{type=\"run-count\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 } },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mik_log{type=\"topics\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Entries",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 214 },
   "targets": [
    {
     "expr": "mik_log{type=\"entries\"}",
     "legendFormat": "{{text}}"
    }
   ]
  },
  {
   "title": "History",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 236 },
   "targets": [
    { "expr": "mik_system_history", "legendFormat": "{{text}}" }
   ]
  },
  {
   "title": "Web Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 258 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mik_ip_proxy_connections{type=\"src-count\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Destination Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mik_ip_proxy_connections{type=\"dst-count\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Source Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mik_ip_proxy_connections{type=\"src-bytes\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Destination Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mik_ip_proxy_connections{type=\"dst-bytes\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Netwatch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 259 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timeline",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "targets": [
      { "expr": "mik_tool_netwatch", "legendFormat": "{{comment}}" }
     ]
    }
   ]
  }
 ]
}