{
 "title": "Pinger",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "ping_tcp_port{type=\"table\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "ping_tcp_port{type=\"table\", status=\"offline\"} > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ping_tcp_port{type=\"timeline\"}",
     "legendFormat": "{{host}}:{{port}}"
    }
   ]
  }
 ]
}