{
 "title": "Tinkoff",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "account",
    "query": {
     "query": "query_result(count by (account)(count_over_time(tin_invest_portfolios[10m])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolios{type=\"totalAmountPortfolio\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Yield",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolios{type=\"expectedYield\"})",
     "legendFormat": " "
    },
    {
     "expr": "sum(tin_invest_portfolios{type=\"expectedYield\"}) * 100 / (sum(tin_invest_portfolios{type=\"totalAmountPortfolio\"}) - sum(tin_invest_portfolios{type=\"expectedYield\"}))",
     "legendFormat": " p"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolios{type=\"totalAmountPortfolio\"})",
     "legendFormat": "price"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolios{type=\"expectedYield\"})",
     "legendFormat": "yield"
    },
    {
     "expr": "sum(tin_invest_portfolios{type=\"expectedYield\"}) * 100 / (sum(tin_invest_portfolios{type=\"totalAmountPortfolio\"}) - sum(tin_invest_portfolios{type=\"expectedYield\"}))",
     "legendFormat": "percent"
    }
   ]
  },
  { "title": "Accounts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Account Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "sum by (account) (tin_invest_portfolios{type=\"totalAmountPortfolio\"}) != 0",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Account Yield",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "sum by (account) (tin_invest_portfolios{type=\"expectedYield\"}) != 0",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Account Yield (percent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (account) (tin_invest_portfolios{type=\"expectedYield\"}) * 100 / (sum by (account) (tin_invest_portfolios{type=\"totalAmountPortfolio\"}) - sum by (account) (tin_invest_portfolios{type=\"expectedYield\"}))",
     "legendFormat": "{{account}}"
    }
   ]
  },
  { "title": "Instruments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Instrument Price Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "sum by(instrument) (tin_invest_instruments{type=\"priceTotal\"})",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Instrument Yield Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "sum by(instrument) (tin_invest_instruments{instrument!=\"Рубли\",type=\"yieldTotal\"})",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Instrument Yield Total (percent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instrument) (tin_invest_instruments{instrument!=\"Рубли\",type=\"yieldTotal\"}) * 100 / (sum by (instrument) (tin_invest_instruments{type=\"priceTotal\"}) - sum by (instrument) (tin_invest_instruments{type=\"yieldTotal\"}))",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "Instrument Price One",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "tin_invest_instruments{instrument!=\"Рубли\",type=\"priceOne\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "Instrument Quantity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instrument) (tin_invest_instruments{type=\"quantity\"})",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Account: \"$account\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "account"
  },
  {
   "title": "Account Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tin_invest_portfolios{account=\"$account\", type=\"totalAmountPortfolio\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Account Yield",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tin_invest_portfolios{account=\"$account\", type=\"expectedYield\"}",
     "legendFormat": " "
    },
    {
     "expr": "tin_invest_portfolios{account=\"$account\", type=\"expectedYieldPercent\"}",
     "legendFormat": " p"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "tin_invest_portfolios{account=\"$account\", type=\"totalAmountPortfolio\"}",
     "legendFormat": "price"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "tin_invest_portfolios{account=\"$account\", type=\"expectedYield\"}",
     "legendFormat": "yield"
    },
    {
     "expr": "tin_invest_portfolios{account=\"$account\", type=\"expectedYieldPercent\"}",
     "legendFormat": "percent"
    }
   ]
  },
  {
   "title": "Instrument Price Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "tin_invest_instruments{account=\"$account\", type=\"priceTotal\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "Instrument Yield Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "tin_invest_instruments{account=\"$account\", type=\"yieldTotal\", instrument!=\"Рубли\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "Instrument Yield Total (percent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tin_invest_instruments{account=\"$account\", type=\"yieldPercentTotal\", instrument!=\"Рубли\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "Instrument Price One",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "tin_invest_instruments{account=\"$account\", type=\"priceOne\", instrument!=\"Рубли\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "Instrument Quantity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tin_invest_instruments{account=\"$account\", type=\"quantity\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  }
 ]
}