{
 "title": "A-APKS",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Updated",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aapks{type=\"timestamp-pretty\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total Download Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aapks{type=\"timestamp-duration\"}",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aapks{type=\"apks-size\"}",
     "legendFormat": "{{ext}}"
    }
   ]
  },
  {
   "title": "Apk Download Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aapks{type=\"apks-duration\"}",
     "legendFormat": "{{ext}}"
    }
   ]
  },
  {
   "title": "Apk Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aapks{type=\"apks-size\"}",
     "legendFormat": "{{ext}}"
    }
   ]
  },
  {
   "title": "Counters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "aapks{type=\"apks-count\"}",
     "legendFormat": "apks"
    },
    {
     "expr": "aapks{type=\"providers-count\"}",
     "legendFormat": "providers"
    },
    {
     "expr": "aapks{type=\"errors-count\"}",
     "legendFormat": "errors"
    },
    {
     "expr": "aapks{type=\"ua-count\"}",
     "legendFormat": "ua"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 27, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "aapks{type=\"apks-full\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aapks{type=\"errors-string\"}",
     "legendFormat": "{{ext}}"
    }
   ]
  },
  {
   "title": "UserAgents",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aapks{type=\"ua-string\"}",
     "legendFormat": "{{ext}}"
    }
   ]
  }
 ]
}