{
 "title": "MosOblEIRC",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "account", "query": { "query": "label_values(accountName)" } }
  ]
 },
 "panels": [
  {
   "title": "Все счета",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "sum by (accountName) (mosobleirc_charges)",
     "legendFormat": "{{accountName}}"
    }
   ]
  },
  {
   "title": "Все счётчики",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mosobleirc_meters_dates", "legendFormat": "__auto" }
   ]
  },
  { "title": "$account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "account" },
  {
   "title": "Счёт",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "mosobleirc_charges{accountName=\"$account\"}",
     "legendFormat": "{{service}} ({{measure}})"
    }
   ]
  },
  {
   "title": "Счётчики: переданные показания",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mosobleirc_meters_values{accountName=\"$account\", type=\"total\"}",
     "legendFormat": "{{meterNumber}} | {{meterType}} ({{meterUnit}})"
    }
   ]
  },
  {
   "title": "Счётчики: потребление за месяц",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mosobleirc_meters_values{accountName=\"$account\", type=\"consumption\"}",
     "legendFormat": "{{meterNumber}} | {{meterType}} ({{meterUnit}})"
    }
   ]
  }
 ]
}